In [1]:
import torch
from __future__ import print_function

In [2]:
x= torch.empty(2)
x

tensor([0., 0.])

In [3]:
x1 = torch.rand(2,3)
x1

tensor([[0.7083, 0.6341, 0.6460],
        [0.6272, 0.6577, 0.0530]])

In [4]:
x2 = torch.randint(9,(2,)) # random integer from 0 to 9(exclusive)
x2

tensor([8, 5])

In [5]:
y = torch.ones(3,4, dtype= torch.float16)
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float16)

In [6]:
y.size()

torch.Size([3, 4])

In [7]:
# list to tensor
y1 = torch.tensor(data=[1,2,3,4], dtype= torch.double, device= 'cpu')
y1

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [8]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)
c = a + b
c = torch.add(a,b)  # Several ways for doing Sum or other math functions
b.add_(a)       # inplace add
print(b)

tensor([[0.4141, 0.5380],
        [0.9299, 0.4954]])
tensor([[0.9701, 0.4390],
        [0.5562, 0.7031]])
tensor([[1.3842, 0.9770],
        [1.4862, 1.1986]])


In [9]:
b.type()

'torch.FloatTensor'

In [10]:
# Slicing
torch.manual_seed(42) # force torch to produce same random array!
z = torch.randint(9, (4,5))
print(z)

print(z[2]) # 3rd row
print(z[:,2]) # 3rd column
print(z[2,2]) # (3,3) element / actual value for one element is: z[2,2].item()

tensor([[6, 5, 7, 4, 0],
        [2, 7, 5, 4, 2],
        [4, 4, 8, 0, 0],
        [4, 2, 4, 3, 4]])
tensor([4, 4, 8, 0, 0])
tensor([7, 5, 8, 4])
tensor(8)


In [11]:
# Reshape with "view"
print(z)
print(z.view(2,10))
print(z.view(5,-1))
z # there is no change with original tensor

tensor([[6, 5, 7, 4, 0],
        [2, 7, 5, 4, 2],
        [4, 4, 8, 0, 0],
        [4, 2, 4, 3, 4]])
tensor([[6, 5, 7, 4, 0, 2, 7, 5, 4, 2],
        [4, 4, 8, 0, 0, 4, 2, 4, 3, 4]])
tensor([[6, 5, 7, 4],
        [0, 2, 7, 5],
        [4, 2, 4, 4],
        [8, 0, 0, 4],
        [2, 4, 3, 4]])


tensor([[6, 5, 7, 4, 0],
        [2, 7, 5, 4, 2],
        [4, 4, 8, 0, 0],
        [4, 2, 4, 3, 4]])

In [12]:
# Reshape with "reshape"
print(z)
print(z.reshape(5,-1))
z # there is no change with original tensor

tensor([[6, 5, 7, 4, 0],
        [2, 7, 5, 4, 2],
        [4, 4, 8, 0, 0],
        [4, 2, 4, 3, 4]])
tensor([[6, 5, 7, 4],
        [0, 2, 7, 5],
        [4, 2, 4, 4],
        [8, 0, 0, 4],
        [2, 4, 3, 4]])


tensor([[6, 5, 7, 4, 0],
        [2, 7, 5, 4, 2],
        [4, 4, 8, 0, 0],
        [4, 2, 4, 3, 4]])

In [13]:
z1 = z.resize(5,4)

C:\Users\JHamed\miniconda3\envs\torch_env\lib\site-packages\torch\tensor.py:474: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [14]:
# convert to numpy array
print(x1)
x1_np = x1.numpy()
print(x1_np)
print(type(x1_np))

print('\n')
x1.add_(1) # if we change x1
print(x1)
print(x1_np) # x1_np will change too!

tensor([[0.7083, 0.6341, 0.6460],
        [0.6272, 0.6577, 0.0530]])
[[0.7082795  0.6341088  0.64598256]
 [0.6272141  0.65765196 0.05298179]]
<class 'numpy.ndarray'>


tensor([[1.7083, 1.6341, 1.6460],
        [1.6272, 1.6577, 1.0530]])
[[1.7082795 1.6341088 1.6459825]
 [1.6272141 1.6576519 1.0529819]]


In [31]:
# Device : CPU or GPU
if torch.cuda.is_available():  # if torch.has_cuda: -> bool
    print("GPU")
    device = torch.device("cuda")
else:
    print("CPU only")
    device = torch.device("cpu")
    print(device)

a = torch.tensor([1,2,3], device= device)
print(a.device)

CPU only
cpu
cpu


In [35]:
a.to(device)
# a.to('cuda') # AssertionError: Torch not compiled with CUDA enabled

AssertionError: Torch not compiled with CUDA enabled

In [69]:
a.is_cuda # checks that if a is on cuda or not

False

## Gradiant in Pytorch

In [61]:
# Gradiants
# Only Tensors of floating point and complex dtype can require gradients
t = torch.tensor( [2,3,4], dtype=torch.float , requires_grad= True)
t

tensor([2., 3., 4.], requires_grad=True)

In [62]:
t2 = t + 2
print(t2)
t2.retain_grad() # needed for none leaf variable to keep gradiant

t3 = t2 * 3
print(t3)

tensor([4., 5., 6.], grad_fn=<AddBackward0>)
tensor([12., 15., 18.], grad_fn=<MulBackward0>)


In [63]:
# grad (backward method) can be implicitly created only for scalar outputs
t3.mean().backward() # mean() used to output scalar
t.grad # leaf parameter
t2.grad # non-leaf paramete (retain_grad used in previous cell)

tensor([1., 1., 1.])

In [72]:
# omit requires_grad
print(t)
# one way:
t.requires_grad_(False) # inplace
print(t)
# other way:
#with torch.no_grad:
    # codes runs without grdiant computing
    #pass


tensor([2., 3., 4.])
tensor([2., 3., 4.])


In [6]:
a = torch.tensor([1,2,3], dtype= torch.float, requires_grad= True)
print(a)

for i in range(3):
    output = (a * 3).sum()
    output.backward()
    print(a.grad)
    # we should add a.grad.zero_() in loop to correct calculations

tensor([1., 2., 3.], requires_grad=True)
tensor([3., 3., 3.])
tensor([6., 6., 6.])
tensor([9., 9., 9.])


In [37]:
a

tensor([1., 2., 3.], requires_grad=True)

In [38]:
b= torch.tensor([1,2,6])

In [40]:
torch.where(a != b)

(tensor([2]),)

In [41]:
torch.nonzero(a==b, as_tuple=True)

(tensor([0, 1]),)